/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
  IsInt,
} from "class-validator";

import { CatalogoWhereUniqueInput } from "../../catalogo/base/CatalogoWhereUniqueInput";
import { Type } from "class-transformer";
import { CategoriaWhereUniqueInput } from "../../categoria/base/CategoriaWhereUniqueInput";
import { MarcaWhereUniqueInput } from "../../marca/base/MarcaWhereUniqueInput";

@InputType()
class ProdutoUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  ativo?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => CatalogoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CatalogoWhereUniqueInput)
  @IsOptional()
  @Field(() => CatalogoWhereUniqueInput, {
    nullable: true,
  })
  catalogo?: CatalogoWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CategoriaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoriaWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoriaWhereUniqueInput, {
    nullable: true,
  })
  categoria?: CategoriaWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descricao?: string | null;

  @ApiProperty({
    required: false,
    type: () => MarcaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MarcaWhereUniqueInput)
  @IsOptional()
  @Field(() => MarcaWhereUniqueInput, {
    nullable: true,
  })
  marca?: MarcaWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nome?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  preco?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantidadeEstoque?: number | null;
}

export { ProdutoUpdateInput as ProdutoUpdateInput };
