/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProdutoService } from "../produto.service";
import { ProdutoCreateInput } from "./ProdutoCreateInput";
import { Produto } from "./Produto";
import { ProdutoFindManyArgs } from "./ProdutoFindManyArgs";
import { ProdutoWhereUniqueInput } from "./ProdutoWhereUniqueInput";
import { ProdutoUpdateInput } from "./ProdutoUpdateInput";

export class ProdutoControllerBase {
  constructor(protected readonly service: ProdutoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Produto })
  async createProduto(
    @common.Body() data: ProdutoCreateInput
  ): Promise<Produto> {
    return await this.service.createProduto({
      data: {
        ...data,

        catalogo: data.catalogo
          ? {
              connect: data.catalogo,
            }
          : undefined,

        categoria: data.categoria
          ? {
              connect: data.categoria,
            }
          : undefined,

        marca: data.marca
          ? {
              connect: data.marca,
            }
          : undefined,
      },
      select: {
        ativo: true,

        catalogo: {
          select: {
            id: true,
          },
        },

        categoria: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        descricao: true,
        id: true,

        marca: {
          select: {
            id: true,
          },
        },

        nome: true,
        preco: true,
        quantidadeEstoque: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Produto] })
  @ApiNestedQuery(ProdutoFindManyArgs)
  async produtos(@common.Req() request: Request): Promise<Produto[]> {
    const args = plainToClass(ProdutoFindManyArgs, request.query);
    return this.service.produtos({
      ...args,
      select: {
        ativo: true,

        catalogo: {
          select: {
            id: true,
          },
        },

        categoria: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        descricao: true,
        id: true,

        marca: {
          select: {
            id: true,
          },
        },

        nome: true,
        preco: true,
        quantidadeEstoque: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Produto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async produto(
    @common.Param() params: ProdutoWhereUniqueInput
  ): Promise<Produto | null> {
    const result = await this.service.produto({
      where: params,
      select: {
        ativo: true,

        catalogo: {
          select: {
            id: true,
          },
        },

        categoria: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        descricao: true,
        id: true,

        marca: {
          select: {
            id: true,
          },
        },

        nome: true,
        preco: true,
        quantidadeEstoque: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Produto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProduto(
    @common.Param() params: ProdutoWhereUniqueInput,
    @common.Body() data: ProdutoUpdateInput
  ): Promise<Produto | null> {
    try {
      return await this.service.updateProduto({
        where: params,
        data: {
          ...data,

          catalogo: data.catalogo
            ? {
                connect: data.catalogo,
              }
            : undefined,

          categoria: data.categoria
            ? {
                connect: data.categoria,
              }
            : undefined,

          marca: data.marca
            ? {
                connect: data.marca,
              }
            : undefined,
        },
        select: {
          ativo: true,

          catalogo: {
            select: {
              id: true,
            },
          },

          categoria: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          descricao: true,
          id: true,

          marca: {
            select: {
              id: true,
            },
          },

          nome: true,
          preco: true,
          quantidadeEstoque: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Produto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProduto(
    @common.Param() params: ProdutoWhereUniqueInput
  ): Promise<Produto | null> {
    try {
      return await this.service.deleteProduto({
        where: params,
        select: {
          ativo: true,

          catalogo: {
            select: {
              id: true,
            },
          },

          categoria: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          descricao: true,
          id: true,

          marca: {
            select: {
              id: true,
            },
          },

          nome: true,
          preco: true,
          quantidadeEstoque: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
