/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { CatalogoWhereUniqueInput } from "../../catalogo/base/CatalogoWhereUniqueInput";
import { CategoriaWhereUniqueInput } from "../../categoria/base/CategoriaWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { MarcaWhereUniqueInput } from "../../marca/base/MarcaWhereUniqueInput";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

@InputType()
class ProdutoWhereInput {
  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  ativo?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CatalogoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CatalogoWhereUniqueInput)
  @IsOptional()
  @Field(() => CatalogoWhereUniqueInput, {
    nullable: true,
  })
  catalogo?: CatalogoWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CategoriaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoriaWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoriaWhereUniqueInput, {
    nullable: true,
  })
  categoria?: CategoriaWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  descricao?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MarcaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MarcaWhereUniqueInput)
  @IsOptional()
  @Field(() => MarcaWhereUniqueInput, {
    nullable: true,
  })
  marca?: MarcaWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nome?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  preco?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  quantidadeEstoque?: IntNullableFilter;
}

export { ProdutoWhereInput as ProdutoWhereInput };
