/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Marca } from "./Marca";
import { MarcaCountArgs } from "./MarcaCountArgs";
import { MarcaFindManyArgs } from "./MarcaFindManyArgs";
import { MarcaFindUniqueArgs } from "./MarcaFindUniqueArgs";
import { CreateMarcaArgs } from "./CreateMarcaArgs";
import { UpdateMarcaArgs } from "./UpdateMarcaArgs";
import { DeleteMarcaArgs } from "./DeleteMarcaArgs";
import { ProdutoFindManyArgs } from "../../produto/base/ProdutoFindManyArgs";
import { Produto } from "../../produto/base/Produto";
import { MarcaService } from "../marca.service";
@graphql.Resolver(() => Marca)
export class MarcaResolverBase {
  constructor(protected readonly service: MarcaService) {}

  async _marcasMeta(
    @graphql.Args() args: MarcaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Marca])
  async marcas(@graphql.Args() args: MarcaFindManyArgs): Promise<Marca[]> {
    return this.service.marcas(args);
  }

  @graphql.Query(() => Marca, { nullable: true })
  async marca(
    @graphql.Args() args: MarcaFindUniqueArgs
  ): Promise<Marca | null> {
    const result = await this.service.marca(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Marca)
  async createMarca(@graphql.Args() args: CreateMarcaArgs): Promise<Marca> {
    return await this.service.createMarca({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Marca)
  async updateMarca(
    @graphql.Args() args: UpdateMarcaArgs
  ): Promise<Marca | null> {
    try {
      return await this.service.updateMarca({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Marca)
  async deleteMarca(
    @graphql.Args() args: DeleteMarcaArgs
  ): Promise<Marca | null> {
    try {
      return await this.service.deleteMarca(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Produto], { name: "produtos" })
  async findProdutos(
    @graphql.Parent() parent: Marca,
    @graphql.Args() args: ProdutoFindManyArgs
  ): Promise<Produto[]> {
    const results = await this.service.findProdutos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
