/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MarcaService } from "../marca.service";
import { MarcaCreateInput } from "./MarcaCreateInput";
import { Marca } from "./Marca";
import { MarcaFindManyArgs } from "./MarcaFindManyArgs";
import { MarcaWhereUniqueInput } from "./MarcaWhereUniqueInput";
import { MarcaUpdateInput } from "./MarcaUpdateInput";
import { ProdutoFindManyArgs } from "../../produto/base/ProdutoFindManyArgs";
import { Produto } from "../../produto/base/Produto";
import { ProdutoWhereUniqueInput } from "../../produto/base/ProdutoWhereUniqueInput";

export class MarcaControllerBase {
  constructor(protected readonly service: MarcaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Marca })
  async createMarca(@common.Body() data: MarcaCreateInput): Promise<Marca> {
    return await this.service.createMarca({
      data: data,
      select: {
        createdAt: true,
        descricao: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Marca] })
  @ApiNestedQuery(MarcaFindManyArgs)
  async marcas(@common.Req() request: Request): Promise<Marca[]> {
    const args = plainToClass(MarcaFindManyArgs, request.query);
    return this.service.marcas({
      ...args,
      select: {
        createdAt: true,
        descricao: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Marca })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async marca(
    @common.Param() params: MarcaWhereUniqueInput
  ): Promise<Marca | null> {
    const result = await this.service.marca({
      where: params,
      select: {
        createdAt: true,
        descricao: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Marca })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMarca(
    @common.Param() params: MarcaWhereUniqueInput,
    @common.Body() data: MarcaUpdateInput
  ): Promise<Marca | null> {
    try {
      return await this.service.updateMarca({
        where: params,
        data: data,
        select: {
          createdAt: true,
          descricao: true,
          id: true,
          nome: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Marca })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMarca(
    @common.Param() params: MarcaWhereUniqueInput
  ): Promise<Marca | null> {
    try {
      return await this.service.deleteMarca({
        where: params,
        select: {
          createdAt: true,
          descricao: true,
          id: true,
          nome: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/produtos")
  @ApiNestedQuery(ProdutoFindManyArgs)
  async findProdutos(
    @common.Req() request: Request,
    @common.Param() params: MarcaWhereUniqueInput
  ): Promise<Produto[]> {
    const query = plainToClass(ProdutoFindManyArgs, request.query);
    const results = await this.service.findProdutos(params.id, {
      ...query,
      select: {
        ativo: true,

        catalogo: {
          select: {
            id: true,
          },
        },

        categoria: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        descricao: true,
        id: true,

        marca: {
          select: {
            id: true,
          },
        },

        nome: true,
        preco: true,
        quantidadeEstoque: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/produtos")
  async connectProdutos(
    @common.Param() params: MarcaWhereUniqueInput,
    @common.Body() body: ProdutoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      produtos: {
        connect: body,
      },
    };
    await this.service.updateMarca({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/produtos")
  async updateProdutos(
    @common.Param() params: MarcaWhereUniqueInput,
    @common.Body() body: ProdutoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      produtos: {
        set: body,
      },
    };
    await this.service.updateMarca({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/produtos")
  async disconnectProdutos(
    @common.Param() params: MarcaWhereUniqueInput,
    @common.Body() body: ProdutoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      produtos: {
        disconnect: body,
      },
    };
    await this.service.updateMarca({
      where: params,
      data,
      select: { id: true },
    });
  }
}
