/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Marca as PrismaMarca,
  Produto as PrismaProduto,
} from "@prisma/client";

export class MarcaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.MarcaCountArgs, "select">): Promise<number> {
    return this.prisma.marca.count(args);
  }

  async marcas(args: Prisma.MarcaFindManyArgs): Promise<PrismaMarca[]> {
    return this.prisma.marca.findMany(args);
  }
  async marca(args: Prisma.MarcaFindUniqueArgs): Promise<PrismaMarca | null> {
    return this.prisma.marca.findUnique(args);
  }
  async createMarca(args: Prisma.MarcaCreateArgs): Promise<PrismaMarca> {
    return this.prisma.marca.create(args);
  }
  async updateMarca(args: Prisma.MarcaUpdateArgs): Promise<PrismaMarca> {
    return this.prisma.marca.update(args);
  }
  async deleteMarca(args: Prisma.MarcaDeleteArgs): Promise<PrismaMarca> {
    return this.prisma.marca.delete(args);
  }

  async findProdutos(
    parentId: string,
    args: Prisma.ProdutoFindManyArgs
  ): Promise<PrismaProduto[]> {
    return this.prisma.marca
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .produtos(args);
  }
}
