/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Categoria as PrismaCategoria,
  Produto as PrismaProduto,
} from "@prisma/client";

export class CategoriaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CategoriaCountArgs, "select">
  ): Promise<number> {
    return this.prisma.categoria.count(args);
  }

  async categorias(
    args: Prisma.CategoriaFindManyArgs
  ): Promise<PrismaCategoria[]> {
    return this.prisma.categoria.findMany(args);
  }
  async categoria(
    args: Prisma.CategoriaFindUniqueArgs
  ): Promise<PrismaCategoria | null> {
    return this.prisma.categoria.findUnique(args);
  }
  async createCategoria(
    args: Prisma.CategoriaCreateArgs
  ): Promise<PrismaCategoria> {
    return this.prisma.categoria.create(args);
  }
  async updateCategoria(
    args: Prisma.CategoriaUpdateArgs
  ): Promise<PrismaCategoria> {
    return this.prisma.categoria.update(args);
  }
  async deleteCategoria(
    args: Prisma.CategoriaDeleteArgs
  ): Promise<PrismaCategoria> {
    return this.prisma.categoria.delete(args);
  }

  async findProdutos(
    parentId: string,
    args: Prisma.ProdutoFindManyArgs
  ): Promise<PrismaProduto[]> {
    return this.prisma.categoria
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .produtos(args);
  }
}
