/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Catalogo as PrismaCatalogo,
  Produto as PrismaProduto,
} from "@prisma/client";

export class CatalogoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CatalogoCountArgs, "select">): Promise<number> {
    return this.prisma.catalogo.count(args);
  }

  async catalogos(
    args: Prisma.CatalogoFindManyArgs
  ): Promise<PrismaCatalogo[]> {
    return this.prisma.catalogo.findMany(args);
  }
  async catalogo(
    args: Prisma.CatalogoFindUniqueArgs
  ): Promise<PrismaCatalogo | null> {
    return this.prisma.catalogo.findUnique(args);
  }
  async createCatalogo(
    args: Prisma.CatalogoCreateArgs
  ): Promise<PrismaCatalogo> {
    return this.prisma.catalogo.create(args);
  }
  async updateCatalogo(
    args: Prisma.CatalogoUpdateArgs
  ): Promise<PrismaCatalogo> {
    return this.prisma.catalogo.update(args);
  }
  async deleteCatalogo(
    args: Prisma.CatalogoDeleteArgs
  ): Promise<PrismaCatalogo> {
    return this.prisma.catalogo.delete(args);
  }

  async findProdutos(
    parentId: string,
    args: Prisma.ProdutoFindManyArgs
  ): Promise<PrismaProduto[]> {
    return this.prisma.catalogo
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .produtos(args);
  }
}
