/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CatalogoService } from "../catalogo.service";
import { CatalogoCreateInput } from "./CatalogoCreateInput";
import { Catalogo } from "./Catalogo";
import { CatalogoFindManyArgs } from "./CatalogoFindManyArgs";
import { CatalogoWhereUniqueInput } from "./CatalogoWhereUniqueInput";
import { CatalogoUpdateInput } from "./CatalogoUpdateInput";
import { ProdutoFindManyArgs } from "../../produto/base/ProdutoFindManyArgs";
import { Produto } from "../../produto/base/Produto";
import { ProdutoWhereUniqueInput } from "../../produto/base/ProdutoWhereUniqueInput";

export class CatalogoControllerBase {
  constructor(protected readonly service: CatalogoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Catalogo })
  async createCatalogo(
    @common.Body() data: CatalogoCreateInput
  ): Promise<Catalogo> {
    return await this.service.createCatalogo({
      data: data,
      select: {
        createdAt: true,
        descricao: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Catalogo] })
  @ApiNestedQuery(CatalogoFindManyArgs)
  async catalogos(@common.Req() request: Request): Promise<Catalogo[]> {
    const args = plainToClass(CatalogoFindManyArgs, request.query);
    return this.service.catalogos({
      ...args,
      select: {
        createdAt: true,
        descricao: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Catalogo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async catalogo(
    @common.Param() params: CatalogoWhereUniqueInput
  ): Promise<Catalogo | null> {
    const result = await this.service.catalogo({
      where: params,
      select: {
        createdAt: true,
        descricao: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Catalogo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCatalogo(
    @common.Param() params: CatalogoWhereUniqueInput,
    @common.Body() data: CatalogoUpdateInput
  ): Promise<Catalogo | null> {
    try {
      return await this.service.updateCatalogo({
        where: params,
        data: data,
        select: {
          createdAt: true,
          descricao: true,
          id: true,
          nome: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Catalogo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCatalogo(
    @common.Param() params: CatalogoWhereUniqueInput
  ): Promise<Catalogo | null> {
    try {
      return await this.service.deleteCatalogo({
        where: params,
        select: {
          createdAt: true,
          descricao: true,
          id: true,
          nome: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/produtos")
  @ApiNestedQuery(ProdutoFindManyArgs)
  async findProdutos(
    @common.Req() request: Request,
    @common.Param() params: CatalogoWhereUniqueInput
  ): Promise<Produto[]> {
    const query = plainToClass(ProdutoFindManyArgs, request.query);
    const results = await this.service.findProdutos(params.id, {
      ...query,
      select: {
        ativo: true,

        catalogo: {
          select: {
            id: true,
          },
        },

        categoria: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        descricao: true,
        id: true,

        marca: {
          select: {
            id: true,
          },
        },

        nome: true,
        preco: true,
        quantidadeEstoque: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/produtos")
  async connectProdutos(
    @common.Param() params: CatalogoWhereUniqueInput,
    @common.Body() body: ProdutoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      produtos: {
        connect: body,
      },
    };
    await this.service.updateCatalogo({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/produtos")
  async updateProdutos(
    @common.Param() params: CatalogoWhereUniqueInput,
    @common.Body() body: ProdutoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      produtos: {
        set: body,
      },
    };
    await this.service.updateCatalogo({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/produtos")
  async disconnectProdutos(
    @common.Param() params: CatalogoWhereUniqueInput,
    @common.Body() body: ProdutoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      produtos: {
        disconnect: body,
      },
    };
    await this.service.updateCatalogo({
      where: params,
      data,
      select: { id: true },
    });
  }
}
