/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Catalogo } from "./Catalogo";
import { CatalogoCountArgs } from "./CatalogoCountArgs";
import { CatalogoFindManyArgs } from "./CatalogoFindManyArgs";
import { CatalogoFindUniqueArgs } from "./CatalogoFindUniqueArgs";
import { CreateCatalogoArgs } from "./CreateCatalogoArgs";
import { UpdateCatalogoArgs } from "./UpdateCatalogoArgs";
import { DeleteCatalogoArgs } from "./DeleteCatalogoArgs";
import { ProdutoFindManyArgs } from "../../produto/base/ProdutoFindManyArgs";
import { Produto } from "../../produto/base/Produto";
import { CatalogoService } from "../catalogo.service";
@graphql.Resolver(() => Catalogo)
export class CatalogoResolverBase {
  constructor(protected readonly service: CatalogoService) {}

  async _catalogosMeta(
    @graphql.Args() args: CatalogoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Catalogo])
  async catalogos(
    @graphql.Args() args: CatalogoFindManyArgs
  ): Promise<Catalogo[]> {
    return this.service.catalogos(args);
  }

  @graphql.Query(() => Catalogo, { nullable: true })
  async catalogo(
    @graphql.Args() args: CatalogoFindUniqueArgs
  ): Promise<Catalogo | null> {
    const result = await this.service.catalogo(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Catalogo)
  async createCatalogo(
    @graphql.Args() args: CreateCatalogoArgs
  ): Promise<Catalogo> {
    return await this.service.createCatalogo({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Catalogo)
  async updateCatalogo(
    @graphql.Args() args: UpdateCatalogoArgs
  ): Promise<Catalogo | null> {
    try {
      return await this.service.updateCatalogo({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Catalogo)
  async deleteCatalogo(
    @graphql.Args() args: DeleteCatalogoArgs
  ): Promise<Catalogo | null> {
    try {
      return await this.service.deleteCatalogo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Produto], { name: "produtos" })
  async findProdutos(
    @graphql.Parent() parent: Catalogo,
    @graphql.Args() args: ProdutoFindManyArgs
  ): Promise<Produto[]> {
    const results = await this.service.findProdutos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
